name: ml
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19=hecd8cb5_0
  - certifi=2020.12.5=py38hecd8cb5_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1i=h9ed2024_0
  - pip=20.3.3=py38hecd8cb5_0
  - python=3.8.5=h26836e1_1
  - readline=8.0=h1de35cc_0
  - setuptools=51.3.3=py38hecd8cb5_4
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - category-encoders==2.2.2
    - cffi==1.14.4
    - chardet==4.0.0
    - colorama==0.4.4
    - confuse==1.4.0
    - cycler==0.10.0
    - dabl==0.1.9
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - fastcore==1.3.18
    - htmlmin==0.1.12
    - hypothesis==6.0.2
    - idna==2.10
    - imagehash==4.2.0
    - imbalanced-learn==0.7.0
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-contrib-core==0.3.3
    - jupyter-core==4.7.0
    - jupyter-nbextensions-configurator==0.4.1
    - jupyter-tabnine==1.1.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kaggle==1.5.10
    - kiwisolver==1.3.1
    - liac-arff==2.5.0
    - llvmlite==0.35.0
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - missingno==0.4.2
    - mistune==0.8.4
    - mlxtend==0.18.0
    - mpld3==0.5.2
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.4.3
    - networkx==2.5
    - notebook==6.2.0
    - numba==0.52.0
    - numpy==1.19.5
    - openml==0.11.0
    - packaging==20.8
    - pandas==1.2.0
    - pandas-profiling==2.10.0
    - pandocfilters==1.4.3
    - parso==0.8.1
    - patsy==0.5.1
    - pexpect==4.8.0
    - phik==0.11.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - pretty-errors==1.2.19
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.11
    - ptyprocess==0.7.0
    - pyaml==20.4.0
    - pycparser==2.20
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-slugify==4.0.1
    - pytz==2020.5
    - pywavelets==1.1.1
    - pyyaml==5.4
    - pyzmq==21.0.1
    - requests==2.25.1
    - rise==5.7.1
    - scikit-learn==0.23.0
    - scikit-multiflow==0.5.3
    - scikit-optimize==0.8.1
    - scikit-plot==0.3.7
    - scipy==1.6.0
    - seaborn==0.11.1
    - send2trash==1.5.0
    - six==1.15.0
    - sortedcontainers==2.3.0
    - statsmodels==0.12.1
    - tangled-up-in-unicode==0.0.6
    - terminado==0.9.2
    - testpath==0.4.4
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - tornado==6.1
    - tqdm==4.56.0
    - traitlets==5.0.5
    - urllib3==1.26.2
    - visions==0.6.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xmltodict==0.12.0
    - yellowbrick==1.2
prefix: /Users/brian/anaconda3/envs/ml
